[package]
name = "fuzzy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"
rand = "0.8.5"
csv = "1.1.6"
serde = { version = "1.0.145", features = ["derive"] }
